import { City } from '../interfaces';

export const UK_CITIES: City[] = [
  // England
  { name: 'Bath', code: 'BATH' },
  { name: 'Birmingham', code: 'BHX' },
  { name: 'Bradford', code: 'BRD' },
  { name: 'Brighton & Hove', code: 'BTN' },
  { name: 'Bristol', code: 'BRS' },
  { name: 'Cambridge', code: 'CBG' },
  { name: 'Canterbury', code: 'CTY' },
  { name: 'Carlisle', code: 'CAR' },
  { name: 'Chelmsford', code: 'CHM' },
  { name: 'Chester', code: 'CHG' },
  { name: 'Chichester', code: 'CHI' },
  { name: 'Colchester', code: 'COL' },
  { name: 'Coventry', code: 'COV' },
  { name: 'Derby', code: 'DER' },
  { name: 'Doncaster', code: 'DON' },
  { name: 'Durham', code: 'DUR' },
  { name: 'Ely', code: 'ELY' },
  { name: 'Exeter', code: 'EXE' },
  { name: 'Gloucester', code: 'GLO' },
  { name: 'Hereford', code: 'HFD' },
  { name: 'Kingston upon Hull', code: 'HUL' },
  { name: 'Lancaster', code: 'LAN' },
  { name: 'Leeds', code: 'LDS' },
  { name: 'Leicester', code: 'LEI' },
  { name: 'Lichfield', code: 'LIC' },
  { name: 'Lincoln', code: 'LIN' },
  { name: 'Liverpool', code: 'LPL' },
  { name: 'London', code: 'LON' },
  { name: 'Manchester', code: 'MAN' },
  { name: 'Milton Keynes', code: 'MKY' },
  { name: 'Newcastle upon Tyne', code: 'NCL' },
  { name: 'Norwich', code: 'NRW' },
  { name: 'Nottingham', code: 'NOT' },
  { name: 'Oxford', code: 'OXF' },
  { name: 'Peterborough', code: 'PET' },
  { name: 'Plymouth', code: 'PLY' },
  { name: 'Portsmouth', code: 'PMR' },
  { name: 'Preston', code: 'PRN' },
  { name: 'Ripon', code: 'RIP' },
  { name: 'Salford', code: 'SLF' },
  { name: 'Salisbury', code: 'SLS' },
  { name: 'Sheffield', code: 'SHF' },
  { name: 'Southampton', code: 'SOU' },
  { name: 'Southend-on-Sea', code: 'SOS' },
  { name: 'St Albans', code: 'STA' },
  { name: 'Stoke-on-Trent', code: 'SOT' },
  { name: 'Sunderland', code: 'SUN' },
  { name: 'Truro', code: 'TRU' },
  { name: 'Wakefield', code: 'WAK' },
  { name: 'Wells', code: 'WEL' },
  { name: 'Westminster', code: 'WST' },
  { name: 'Winchester', code: 'WIN' },
  { name: 'Wolverhampton', code: 'WLV' },
  { name: 'Worcester', code: 'WCR' },
  { name: 'York', code: 'YRK' },
  // Scotland
  { name: 'Aberdeen', code: 'ABD' },
  { name: 'Dundee', code: 'DND' },
  { name: 'Dunfermline', code: 'DFM' },
  { name: 'Edinburgh', code: 'EDI' },
  { name: 'Glasgow', code: 'GLA' },
  { name: 'Inverness', code: 'INV' },
  { name: 'Perth', code: 'PER' },
  { name: 'Stirling', code: 'STI' },
  // Wales
  { name: 'Bangor', code: 'BGR' },
  { name: 'Cardiff', code: 'CRD' },
  { name: 'Newport', code: 'NWP' },
  { name: 'St Asaph', code: 'SAS' },
  { name: 'St Davids', code: 'SDA' },
  { name: 'Swansea', code: 'SWA' },
  { name: 'Wrexham', code: 'WXM' },
  // Northern Ireland
  { name: 'Armagh', code: 'ARM' },
  { name: 'Bangor', code: 'BGN' },
  { name: 'Belfast', code: 'BFS' },
  { name: 'Lisburn', code: 'LIS' },
  { name: 'Londonderry', code: 'LDY' },
  { name: 'Newry', code: 'NRY' },
];
